logging:
  level:
    root: info

server:
  tomcat:
    #max-connections: 8192
    max-connections: 2
    #accept-count: 100
    connection-timeout: 20s # 60s
    threads:
      #max: 200
      max: 2
      #min-spare: 1
    #keep-alive-timeout: -1
